version: '3'
services: 
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    image: "node:14"
    container_name: api-container
    working_dir: /app
    restart: always
    command: yarn start
    volumes:
      - ./:/app
    ports:
      - "5050:5050"
    links: 
      - mongo